### ISSUE TITLE
Dieb doesn't work

### ISSUE THREAD

**Issue by cravay** [card-game-dev/card-game#14]
```
ReferenceError: enemyHand is not defined
    at Conditions.enemyMoreCards (/var/www/default/card-game/js_module/Conditions.js:488:7)
    at Dieb.isPlayable (/var/www/default/card-game/js_module/cards/objects/Dieb.js:21:13)
    at Player.getPlayOptions (/var/www/default/card-game/js_module/Player.js:70:14)
    at Game.playOptions (/var/www/default/card-game/js_module/Game.js:95:30)
    at Game.start (/var/www/default/card-game/js_module/Game.js:75:8)
    at startGame (/var/www/default/card-game/server.js:114:7)
    at Socket.<anonymous> (/var/www/default/card-game/server.js:68:4)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Socket.onevent (/var/www/default/card-game/node_modules/socket.io/lib/socket.js:335:8)
```

**Comment by ceoy** [comment]
fixed with commit 212, ty timmmmmb
